### ISSUE TITLE
Bug with notifications

### ISSUE THREAD

**Issue by stom79** [stom79/mastalab#25]

**Comment by stom79** [comment]
@PhotonQyv I remember you told me that you were affected by this bug. Could you try the last fix I put? Thanks!

**Comment by stom79** [comment]
@PhotonQyv I merged the fix in develop. It's about this [piece of code](https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/client/API.java#L1231-L1244)

**Comment by PhotonQyv** [comment]
@stom79 I'll take a look, and let you know (:*

**Comment by PhotonQyv** [comment]
@stom79 Still doesn't appear to be working completely, though the notification tab gets a bubble with new notifications, not so far had a notification while I'm not in Mastalab. Saving pictures does still trigger an external notification.

**Comment by stom79** [comment]
@PhotonQyv OK. I pushed a fix in develop.

**Comment by PhotonQyv** [comment]
@stom79 Ok, just built and checking it now (:*

**Comment by PhotonQyv** [comment]
@stom79 Ok, now getting notifications, but Mastalab crashes immediately after receiving them.

**Comment by PhotonQyv** [comment]
@stom79 Here you go, didn't even click on it, it just boop'd and mastalab crashed.

![2017-11-06 13 42 17](https://user-images.githubusercontent.com/27952685/32443994-f60a08fc-c2f8-11e7-8980-59e58b0a7d4c.png)

**Comment by stom79** [comment]
@PhotonQyv I should not debug during my lunchtime break. I pushed another fix :)

**Comment by PhotonQyv** [comment]
@stom79 I'll check it out.

**Comment by PhotonQyv** [comment]
@stom79 That's better, getting some boops now (:* Crash fixed.

**Comment by stom79** [comment]
Great! Thank you.
