### ISSUE TITLE
Default Post Privacy Overridden

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#329]
When making posts, your default post privacy is overridden "upwards." In other words, if your default privacy is private, and you reply to a public post, your privacy is made public for that reply.

This is not how it works by default on Mastodon's web UI, and if this is going to be a feature, it should be optional and preferably non-default. The only time you should inherit privacy is "downward," eg if you default to public posts and reply to a private post your reply is private.

---

Instance: Sins.center (probably doesn't matter)

Mastalab version: 1.8.1

Android version: 7.0

**Comment by stom79** [comment]
It was fixed in #59 and I guess I broke it when fixing #300.

**Comment by stom79** [comment]
Can you test [this apk](https://github.com/stom79/mastalab/blob/26a3be8650ebc0c35ea3bac71e8beebbd3da6ef4/app/playstore/release/app-playstore-release-1.8.2.apk?raw=true). Thanks

**Comment by Fidgetcetera** [comment]
I didn't get the chance to test this due to college, sorry! as of 1.8.3, what now happens is still not quite right though. all replies on private accounts become private, even if your default is different. The behavior is unchanged on non-private accounts.

to lay out the expected behavior, I'm going to number the post privacies. 4 is public, 3 is unlisted, 2 is private, 1 is direct.

expected: when replying, if default privacy is less than original post's privacy, use default.
if default is greater than original post's privacy, use original post's. 
this should happen no matter if the *account* is private or public. only post privacy matters here.

example: default privacy is unlisted. 
if I reply to a direct message, my reply privacy should also be direct. if I reply to a public post, my reply privacy should be unlisted.

**Comment by stom79** [comment]
> expected: when replying, if default privacy is less than original post's privacy, use default.
> if default is greater than original post's privacy, use original post's.
> this should happen no matter if the account is private or public.

What privacy did you define in the app settings? Because it also depends of that.

**Comment by Fidgetcetera** [comment]
When I said "default" privacy, I meant the privacy set in settings. 
my default privacy on an account in app settings is set to unlisted (do not post to public timeline) but because the account is private, when I reply to any posts, even my own unlisted ones, it sets the post privacy to followers-only/private.

**Comment by stom79** [comment]
Ok. Thank you, it's fixed.
