### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by GeekElite** [stom79/mastalab#37]
No matter what I type in the Instance field, the "Login" button is inactive/unclickable. I've tried all three of my Mastodon accounts on both my Pixel XL and my Galaxy Tab S 10.5, and nothing works. I've tried my short username, full username, just the instance, and any number of other random entries with the same result. I don't have the same issue on other clients (like tootdon).

On my Pixel XL, a message popped up while I was typing in my username, but it flashes on and off so fast I can't read it. I have no idea how to solve the problem.

**Comment by stom79** [comment]
Thanks for this report. It sounds the app can't get a client id (the short message which should be displayed). 
- Did you use the autocomplete feature to get your instance name? Does it work?
- Are these accounts on different instances?

You used two different devices, I guess they are not on the same OS version, so it might not be related to it.

**Comment by GeekElite** [comment]
I did not use any autocomplete function with one (possible) exception: when I open the app, the Instance field is already filled with "Instance: mastadon.social", and I tried logging in without changing that. (Yes, all of my ID's are on mastadon.social).

Aside from that, I just typed everything in, and was never prompted for any auto-completes.

**Comment by stom79** [comment]
Oh Ok. That's the problem. In fact, it's a placeholder (displayed as an example) but you need to fill this form by writing "mastodon.social".
As soon as this field will lose the focus, the client id will be retrieved and if it's ok, the login button will be enabled.

**Comment by GeekElite** [comment]
I tried that, as well. I tried all kinds of things in that field, and none of them worked.

**Comment by stom79** [comment]
OK. This is how it should work.

![device-2017-11-13-191107](https://user-images.githubusercontent.com/30171182/32741468-9fbd86f0-c8a6-11e7-89de-034c22134a34.png)
![device-2017-11-13-191151](https://user-images.githubusercontent.com/30171182/32741470-9fe318ca-c8a6-11e7-8052-05a32bac094b.png)

**Comment by GeekElite** [comment]
Yes. I've typed those exact words into the instance field and it still doesn't work.

After your response above, I allowed the autocomplete to work as you detail. It still doesn't work.

**Comment by GeekElite** [comment]
Okay, Progress: Using Autocomplete worked on my Pixel XL. It still does not work my my Galaxy Tab.

That said, *not* using autocomplete - just typing in "mastodon.social" on my Pixel XL still did *not* work.

But, I'm in on my phone, just not my tablet.

**Comment by stom79** [comment]
Thanks for tests.

That's weird! I will investigate for tablets.

**Comment by happyGNU** [comment]
Confirmed on LineageOS (Android 7.1.2) with Mastalab (1.5.7) from F-Droid and scholar.social instance. 

I read this bug and followed same instructions. I still can't connect.

**Comment by stom79** [comment]
@happyGNU I don't know what is your Android version. But if it is below KitKat release (ie Android < 4.4), it sounds to be an issue with cipher suites. See the report on [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=scholar.social&latest).
Unfortunately, only the release of Mastalab published on Google Play can work for these devices. 

![capture d ecran 2017-11-13 a 21 01 33](https://user-images.githubusercontent.com/30171182/32746445-ee8e7802-c8b5-11e7-82c9-70fb9172128e.png)

**Comment by stom79** [comment]
@happyGNU I will investigate. scholar.social should work on Android 7.

**Comment by happyGNU** [comment]
When I select it from drop drown menu and then press email this is what I get 

![screenshot_20171113-150732](https://user-images.githubusercontent.com/22283638/32751875-d8dcf9da-c88c-11e7-9d16-f177bd2f21a6.png)

**Comment by stom79** [comment]
Could you disable Tor and try again?

**Comment by mike-burns** [comment]
I can confirm that I am seeing this issue when connected via LTE but not via WiFi -it works fine on WiFi.

Instance: `mastodon.technology`
Android: 8.0.0 -October 5, 2017
Device: Pixel
Mastalab: 1.5.7

Works fine with `mastodon.social` and `retro.social` on both LTE and WiFi.

**Comment by stom79** [comment]
@happyGNU It seems the instance is down. 

@mike-burns Thanks for these details.

I increased the timeout which was too short (10s to 30s). It seems some servers are busier recently which can explain why the app can't get the client id.

**Comment by stom79** [comment]
Could you please check if it's fixed in [1.6.0-rc-1](https://github.com/stom79/mastalab/releases/tag/1.6.0-rc-1). APKs can be downloaded on this page.

**Comment by creideiki** [comment]
I have the same issue (Motorola Moto G5, Android 8.0.0, LineageOS 15.0, no Google Play services installed, getting Mastalab through F-Droid, server `mastodon.social`.).

With 1.6.0-rc-1, I no longer get the "cannot get client ID" pop-up, and I can press the "Login" button, but when I do I get an error pop-up saying "Can not log in!".

`adb logcat` says (when pressing "Login"):
```
W System.err: java.io.FileNotFoundException: https://mastodon.social/oauth/token
W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
W System.err:    at fr.gouv.etalab.mastodon.client.HttpsConnection.post(HttpsConnection.java:159)
W System.err:    at fr.gouv.etalab.mastodon.activities.BaseLoginActivity$5$1.run(BaseLoginActivity.java:273)
W System.err:    at java.lang.Thread.run(Thread.java:764)
```

**Comment by stom79** [comment]
@creideiki Thanks. I fixed this issue and I upload the [fix](https://github.com/stom79/mastalab/blob/a8ded0d2720b0c1ef2311b517fbeedc8aa420f4e/app/fdroid/release/app-fdroid-release-1.6.0-rc-1-fix.apk?raw=true).

**Comment by creideiki** [comment]
I'm still getting the same exception:
```
W System.err: java.io.FileNotFoundException: https://mastodon.social/oauth/token
W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
W System.err:    at fr.gouv.etalab.mastodon.client.HttpsConnection.post(HttpsConnection.java:157)
W System.err:    at fr.gouv.etalab.mastodon.activities.BaseLoginActivity$5$1.run(BaseLoginActivity.java:273)
W System.err:    at java.lang.Thread.run(Thread.java:764)
```
There's a new line number for `HttpsConnection.java:157`, so that should indicate that the new code is running..

**Comment by happyGNU** [comment]
Thanks @stom79 :) it works now !!

**Comment by stom79** [comment]
@creideiki OK. I uploaded another [apk](https://github.com/stom79/mastalab/blob/develop/app/fdroid/release/app-fdroid-release-1.6.0-rc-1-fix2.apk?raw=true).

**Comment by creideiki** [comment]
Still the same error (now at `HttpsConnection.java:156`).

**Comment by stom79** [comment]
@creideiki And by using the "two-step authentication" link, does it work?

**Comment by creideiki** [comment]
Oh, hey! I had not noticed that, since it isn't there at first, and when it does appear, ~30 seconds after I start typing, it's covered by the on-screen keyboard.

Clicking it asks me for e-mail and password again, then TOTP code, and then gives me a page saying:
```
Application Mastalab requests access to your account

It will be able to read your account's data, post on your behalf, and follow, block, unblock and unfollow accounts

[AUTHORIZE]
[DENY]
```
Clicking `Authorize` does nothing visible at all, either on screen or in `adb logcat`. Clicking `Deny` brings me back to the first page, with an error pop-up saying `The instance did not return an authrisation code`.

**Comment by stom79** [comment]
Thanks, I will fix that asap. I didn't test it since I removed the loopj lib. This message should be displayed as soon as the client id is retrieved. I will update the message by adding " / authentication problems?".

**Comment by stom79** [comment]
Here is the [fix](https://github.com/stom79/mastalab/blob/develop/app/fdroid/release/app-fdroid-release-1.6.0-rc-1-fix3.apk?raw=true).

**Comment by creideiki** [comment]
That works!

**Comment by stom79** [comment]
Thanks for your contribution.

**Comment by SinaCutie** [comment]
When will this be making it as an update via Google Play? I am having this issue as well, and would really like to use Mastalab.

**Comment by stom79** [comment]
@SinaCutie It's on the beta channel. Or you can simply download it [here](https://github.com/stom79/mastalab/releases/download/1.6.0/app-safetynet-release-1.6.0.apk).
