### ISSUE TITLE
Crashes in beta from 2017/12/02

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#75]
I'm having somewhat frequent crashes in the beta released yesterday.

It most frequently happens when returning to the app from a notification. I think it has happened other times, but I can't verify those, so let's assume it's notification related. I've sent logs through the play store crash reporter.
---

Instance: glitch.social, anticapitalist.party, ephemeral.glitch.social

Mastalab version: 1.6.4

LineageOS 14.1 (Android 7.1)
Android version:

**Comment by stom79** [comment]
Yes, you are absolutely right about how this bug occurs. I published the fix: [1.6.4.1](https://github.com/stom79/mastalab/releases/1.6.4.1). It has also been published in Play Store.

**Comment by jfmcbrayer** [comment]
I will verify as soon as I get a notification :)

**Comment by jfmcbrayer** [comment]
I also had very high battery usage in 1.6.4, possibly due to this bug, possibly to animated gif avatars. But I will wait to report this until I can verify it still happens with 1.6.4.1.

**Comment by stom79** [comment]
Interesting! I think I will disable by default animated avatars in the next release.

**Comment by stom79** [comment]
If crashes are solved, I will close this issue and open a new one for battery if it's confirmed.

**Comment by jfmcbrayer** [comment]
Crashes are solved; battery issue does not seem to be reproducible.

**Comment by stom79** [comment]
OK. Thanks! I close this issue.
